// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGGpUMaZSRXhJgyFagcFQUHFZFpeNjyZg',
    appId: '1:834114860032:web:1d294360ad479ab64c54e5',
    messagingSenderId: '834114860032',
    projectId: 'itec315shoppinglist',
    authDomain: 'itec315shoppinglist.firebaseapp.com',
    storageBucket: 'itec315shoppinglist.firebasestorage.app',
    measurementId: 'G-T7KRC9C8VX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA19kGIOYGCQcGyuGL_PmmNSoBzD-Li8n4',
    appId: '1:834114860032:android:1c47d5b85bbb81194c54e5',
    messagingSenderId: '834114860032',
    projectId: 'itec315shoppinglist',
    storageBucket: 'itec315shoppinglist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQo5nIdBwAInfidNMqW2qkh95fx1NSiRE',
    appId: '1:834114860032:ios:aaa8724b6d91c7db4c54e5',
    messagingSenderId: '834114860032',
    projectId: 'itec315shoppinglist',
    storageBucket: 'itec315shoppinglist.firebasestorage.app',
    iosBundleId: 'com.example.shoppingList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQo5nIdBwAInfidNMqW2qkh95fx1NSiRE',
    appId: '1:834114860032:ios:aaa8724b6d91c7db4c54e5',
    messagingSenderId: '834114860032',
    projectId: 'itec315shoppinglist',
    storageBucket: 'itec315shoppinglist.firebasestorage.app',
    iosBundleId: 'com.example.shoppingList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGGpUMaZSRXhJgyFagcFQUHFZFpeNjyZg',
    appId: '1:834114860032:web:6c4e425415d7ca9f4c54e5',
    messagingSenderId: '834114860032',
    projectId: 'itec315shoppinglist',
    authDomain: 'itec315shoppinglist.firebaseapp.com',
    storageBucket: 'itec315shoppinglist.firebasestorage.app',
    measurementId: 'G-C3P1B15LMB',
  );

}